# ========================
# Spring 組態
# ========================
spring:
  application:
    name: springBootSample
  security:
    user:
      name: admin
      password: admin

# ========================
# Log4j2 組態
# ========================
logging:
  config: classpath:logging/log4j2.xml